### ISSUE TITLE
Hitting an error while downloading at same point each time

### ISSUE THREAD

**Issue by sheepdog817** [vassim/linuxacademy-dl#32] opened 2017-04-18 03:09 UTC
Attempting to download videos for the free AWS Certified Solutions Architect Course for reference.

INFO     Skipping already existing file /root/git/16 - RDS (Relational Database Service)/1 - RDS Essentials.mp4
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 140, in download
    self.analyze()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 136, in analyze
    self._resources = self.get_resources()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 133, in get_resources
    return processor()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 108, in __call__
    return self.process()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 71, in process
    play_list_url = self.get_m3u8_playlist_url(lesson_page_source)
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 64, in get_m3u8_playlist_url
    return LessonProcessor.m3u8_grabber.findall(lesson_page_source)[0]
IndexError: list index out of range
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.

**Comment by sheepdog817** [comment] 2017-04-23 20:21
Any chance on this receiving a fix before the AWS course rotates out at the end of the month? Thanks!

**Comment by vassim** [comment] 2017-04-27 10:29
Hi @sheepdog817, Thank you for reporting this issue. I think this issue is beyond the scope of this project. The course you are referring here had some missing videos before ("RDS Essentials" was one of 'em) and this problem was happening because of that.
It seems like the Linux Academy team has already fixed the issue and re uploaded the video. If you are facing similar kind of issues in future, please make sure that the videos are playable on-line, if not, please report the issue there!
(Duplicate of #29)

**Closed by vassim** 2017-04-27 10:29 UTC
Labels: Invalid, WontFix

**Comment by sheepdog817** [comment] 2017-04-27 16:06
Thanks for the reply @vassim! Attempted to pull again and am still coming across the same issue. It may be a good idea to add a small bit of logic to skip over broken videos. It may be an issue with Linux Academy videos, but your program fails if everything is not 100% correct on their end. I am going to attempt to debug this myself and add the code necessary to skip over broken videos.
