### ISSUE TITLE
ERROR Unknown Exception + Download partially failed

### ISSUE THREAD

**Issue by lynecker** [vassim/linuxacademy-dl#2] opened 2017-01-04 08:21 UTC
**When i try to download with any course it's show this error :** 
```
ERROR    Unknown Exception
ERROR    'NoneType' object is not iterable
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\linuxacademy_dl\cli.py", line 150, in main

    la.download()
  File "c:\python27\lib\site-packages\linuxacademy_dl\linux_academy.py", line 15
5, in download
    self._course.download()
  File "c:\python27\lib\site-packages\linuxacademy_dl\course.py", line 99, in do
wnload
    asset.download()
  File "c:\python27\lib\site-packages\linuxacademy_dl\assets.py", line 131, in d
ownload
    for resource in self._resources:
TypeError: 'NoneType' object is not iterable
```

And When i am download this course _"https://linuxacademy.com/cp/modules/view/id/13"_ all its okay. 
but when i am download this course _"https://linuxacademy.com/cp/modules/view/id/38"_ only some of which can be downloaded, maybe 3 or 4 folder can downloaded.

**Comment by vassim** [comment] 2017-01-04 12:11
Thank you for your report. It looks like a duplicate of #1. I fixed it already!

**Closed** 2017-01-04 12:12 UTC
Labels: 1.0.dev2, duplicate
