### ISSUE TITLE
Getting errors and download breaks

### ISSUE THREAD

**Issue by umarmurtaza** [vassim/linuxacademy-dl#28] opened 2017-03-31 12:31 UTC
I have the latest version:
osboxes@osboxes:~$ linuxacademy-dl --version
linuxacademy-dl 1.0a3

Here the logs, please check:

osboxes@osboxes:~/linuxacademy/Running Container Clusters with Kubernetes$ linuxacademy-dl --debug https://linuxacademy.com/cp/modules/view/id/80

```
INFO     Debug log file created at /home/osboxes/linuxacademy-dl/log/log_2017-03-31T13:08:31.309154.log
DEBUG    Python: CPython 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
DEBUG    Platform: Linux-4.8.0-41-generic-x86_64-with-Ubuntu-16.04-xenial [#44~16.04.1-Ubuntu SMP Fri Mar 3 17:11:16 UTC 2017]
DEBUG    OS: Linux - Ubuntu 16.04 xenial
INFO     Logging in ...
INFO     Analyzing ...
INFO     Downloading files ...
INFO     Skipping already existing file /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/3 - Docker Fundamentals/1 - Pulling an Image.mp4
INFO     Skipping already existing file /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/3 - Docker Fundamentals/2 - Running Containers.mp4
INFO     Skipping already existing file /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/3 - Docker Fundamentals/3 - The Dockerfile.mp4
INFO     Skipping already existing file /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/3 - Docker Fundamentals/4 - Managing Ports with Container Deployments.mp4
INFO     Skipping already existing file /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/1 - Introduction/1 - Course Syllabus.mp4
INFO     Skipping already existing file /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/1 - Introduction/2 - Introduction to Kubernetes.mp4
INFO     Skipping already existing file /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/1 - Introduction/3 - Introduction to Docker.mp4
INFO     Skipping already existing file /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/1 - Introduction/4 - Containers vs. Virtual Machines.mp4
INFO     Skipping already existing file /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/1 - Introduction/5 - Docker Architecture.mp4
INFO     Skipping already existing file /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/1 - Introduction/6 - The Docker Hub.mp4
INFO     Skipping already existing file /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/1 - Introduction/7 - Kubernetes Architecture.mp4
INFO     Downloading /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/1 - Introduction/8 - Introduction to YAML.mp4
INFO     Downloaded /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/1 - Introduction/8 - Introduction to YAML.mp4
INFO     Downloading /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/4 - Pods, Tags and Services/1 - Create and Deploy Pod Definitions.mp4
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    ('Connection broken: error("(104, \'ECONNRESET\')",)', error("(104, 'ECONNRESET')",))
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 135, in download
    self.save_to
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/downloader.py", line 119, in __call__
    self.hls_download(download_info, final_path)
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/downloader.py", line 80, in hls_download
    itm.raw, hls_data['key'], iv
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/hls_decrypt.py", line 83, in decrypt
    cipher.decrypt(self.chunk_stream.read(1024 * AES.block_size))
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 397, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 316, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
ProtocolError: ('Connection broken: error("(104, \'ECONNRESET\')",)', error("(104, 'ECONNRESET')",))
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.
osboxes@osboxes:~/linuxacademy/Running Container Clusters with Kubernetes$ ^C
```

**Comment by umarmurtaza** [comment] 2017-03-31 12:32
sending the logs again ....



osboxes@osboxes:~/linuxacademy/Running Container Clusters with Kubernetes$ linuxacademy-dl --debug https://linuxacademy.com/cp/modules/view/id/80

INFO     Debug log file created at /home/osboxes/linuxacademy-dl/log/log_2017-03-31T13:08:31.309154.log
DEBUG    Python: CPython 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
DEBUG    Platform: Linux-4.8.0-41-generic-x86_64-with-Ubuntu-16.04-xenial [44~16.04.1-Ubuntu SMP Fri Mar 3 17:11:16 UTC 2017]
DEBUG    OS: Linux - Ubuntu 16.04 xenial
INFO     Logging in ...
INFO     Analyzing ...
INFO     Downloading files ...
INFO     Skipping already existing file /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/3 - Docker Fundamentals/1 - Pulling an Image.mp4
INFO     Skipping already existing file /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/3 - Docker Fundamentals/2 - Running Containers.mp4
INFO     Skipping already existing file /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/3 - Docker Fundamentals/3 - The Dockerfile.mp4
INFO     Skipping already existing file /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/3 - Docker Fundamentals/4 - Managing Ports with Container Deployments.mp4
INFO     Skipping already existing file /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/1 - Introduction/1 - Course Syllabus.mp4
INFO     Skipping already existing file /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/1 - Introduction/2 - Introduction to Kubernetes.mp4
INFO     Skipping already existing file /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/1 - Introduction/3 - Introduction to Docker.mp4
INFO     Skipping already existing file /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/1 - Introduction/4 - Containers vs. Virtual Machines.mp4
INFO     Skipping already existing file /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/1 - Introduction/5 - Docker Architecture.mp4
INFO     Skipping already existing file /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/1 - Introduction/6 - The Docker Hub.mp4
INFO     Skipping already existing file /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/1 - Introduction/7 - Kubernetes Architecture.mp4
INFO     Downloading /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/1 - Introduction/8 - Introduction to YAML.mp4
INFO     Downloaded /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/1 - Introduction/8 - Introduction to YAML.mp4
INFO     Downloading /home/osboxes/linuxacademy/Running Container Clusters with Kubernetes/4 - Pods, Tags and Services/1 - Create and Deploy Pod Definitions.mp4
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    ('Connection broken: error("(104, \'ECONNRESET\')",)', error("(104, 'ECONNRESET')",))
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 135, in download
    self.save_to
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/downloader.py", line 119, in __call__
    self.hls_download(download_info, final_path)
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/downloader.py", line 80, in hls_download
    itm.raw, hls_data['key'], iv
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/hls_decrypt.py", line 83, in decrypt
    cipher.decrypt(self.chunk_stream.read(1024 * AES.block_size))
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 397, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 316, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
ProtocolError: ('Connection broken: error("(104, \'ECONNRESET\')",)', error("(104, 'ECONNRESET')",))
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.
osboxes@osboxes:~/linuxacademy/Running Container Clusters with Kubernetes$ ^C

**Comment by umarmurtaza** [comment] 2017-03-31 12:34
dont know why the above logs are showing up as stroked :(

**Comment by vassim** [comment] 2017-04-03 13:54
Hi @umarmurtaza , Thank you for reporting this issue. I think it is a duplicate of #19.

**Closed by vassim** 2017-04-03 13:54 UTC
Labels: Bug, Duplicate
