### ISSUE TITLE
Connection broken: error

### ISSUE THREAD

**Issue by icecrystal99** [vassim/linuxacademy-dl#24] opened 2017-03-19 15:43 UTC
When i try to download something, i get the following error:

> INFO     Downloaded /home/Documents/LinuxAcademy/Linux_Essentials_Certification/13 - Turning Commands into a Script/1 - Basic Text Editing.mp4
INFO     Downloading /home/Documents/LinuxAcademy/Linux_Essentials_Certification/13 - Turning Commands into a Script/2 - Basic Shell Scripting.mp4
INFO     Downloaded /home/Documents/LinuxAcademy/Linux_Essentials_Certification/13 - Turning Commands into a Script/2 - Basic Shell Scripting.mp4
INFO     Downloading /Documents/LinuxAcademy/Linux_Essentials_Certification/13 - Turning Commands into a Script/3 - Basic Shell Scripting, Continued.mp4
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))
Traceback (most recent call last):
  File "/home/.local/lib/python2.7/site-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/home/.local/lib/python2.7/site-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/home/.local/lib/python2.7/site-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/home/.local/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 135, in download
    self.save_to
  File "/home/.local/lib/python2.7/site-packages/linuxacademy_dl/downloader.py", line 119, in __call__
    self.hls_download(download_info, final_path)
  File "/home/.local/lib/python2.7/site-packages/linuxacademy_dl/downloader.py", line 80, in hls_download
    itm.raw, hls_data['key'], iv
  File "/home/.local/lib/python2.7/site-packages/linuxacademy_dl/hls_decrypt.py", line 83, in decrypt
    cipher.decrypt(self.chunk_stream.read(1024 * AES.block_size))
  File "/home/.local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 397, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/.local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 316, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
ProtocolError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.

**Comment by vassim** [comment] 2017-03-24 14:00
Possible duplicate of #19

**Closed** 2017-03-24 14:00 UTC
Labels: Bug, Duplicate
